//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA_MVC_StudentInfo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FSE_ProjectEntities : DbContext
    {
        public FSE_ProjectEntities()
            : base("name=FSE_ProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Parent_Task> Parent_Task { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Task_Detail> Task_Detail { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
