//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA_MVC_StudentInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parent_Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Parent_Task()
        {
            this.Task_Detail = new HashSet<Task_Detail>();
        }
    
        public int Parent_ID { get; set; }
        public string Parent_Task1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_Detail> Task_Detail { get; set; }
    }
}
